var searchData=
[
  ['v_5fformatter_0',['v_formatter',['../classspdlog_1_1details_1_1v__formatter.html',1,'spdlog::details']]],
  ['va_5flist_1',['va_list',['http://en.cppreference.com/w/cpp/utility/variadic/va_list.html',1,'']]],
  ['valarray_2',['valarray',['http://en.cppreference.com/w/cpp/numeric/valarray.html',1,'std']]],
  ['value_3',['value',['../unionarg__ref_1_1value.html',1,'arg_ref&lt; Char &gt;::value'],['../classvalue.html',1,'value&lt; Context &gt;']]],
  ['value_5fcompare_4',['value_compare',['http://en.cppreference.com/w/cpp/container/map/value_compare.html',1,'std::map::value_compare'],['http://en.cppreference.com/w/cpp/container/multimap/value_compare.html',1,'std::multimap::value_compare'],['http://en.cppreference.com/w/cpp/container/map/value_compare.html',1,'std::pmr::map::value_compare'],['http://en.cppreference.com/w/cpp/container/multimap/value_compare.html',1,'std::pmr::multimap::value_compare']]],
  ['value_5ftype_5',['value_type',['../structdetail_1_1counting__iterator_1_1value__type.html',1,'detail::counting_iterator']]],
  ['variant_6',['variant',['http://en.cppreference.com/w/cpp/utility/variant.html',1,'std']]],
  ['variant_5falternative_7',['variant_alternative',['http://en.cppreference.com/w/cpp/utility/variant/variant_alternative.html',1,'std']]],
  ['variant_5falternative_5ft_8',['variant_alternative_t',['http://en.cppreference.com/w/cpp/utility/variant/variant_alternative.html',1,'std']]],
  ['variant_5fsize_9',['variant_size',['http://en.cppreference.com/w/cpp/utility/variant/variant_size.html',1,'std']]],
  ['vector_10',['vector',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std::pmr::vector'],['http://en.cppreference.com/w/cpp/container/vector.html',1,'std::vector']]],
  ['vector_3c_20basic_5fformat_5farg_3c_20context_20_3e_20_3e_11',['vector&lt; basic_format_arg&lt; Context &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20catch_3a_3agenerators_3a_3ageneratorwrapper_3c_20t_20_3e_20_3e_12',['vector&lt; Catch::Generators::GeneratorWrapper&lt; T &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20catch_3a_3amatchers_3a_3aimpl_3a_3amatcherbase_3c_20argt_20_3e_20const_20_2a_20_3e_13',['vector&lt; Catch::Matchers::Impl::MatcherBase&lt; ArgT &gt; const * &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20catch_3a_3amessageinfo_20_3e_14',['vector&lt; Catch::MessageInfo &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20char_20_3e_15',['vector&lt; char &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20detail_3a_3anamed_5farg_5finfo_3c_20char_5ftype_20_3e_20_3e_16',['vector&lt; detail::named_arg_info&lt; char_type &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20item_5ftype_20_3e_17',['vector&lt; item_type &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20spdlog_3a_3adetails_3a_3alog_5fmsg_5fbuffer_20_3e_18',['vector&lt; spdlog::details::log_msg_buffer &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3apair_3c_20int_2c_20std_3a_3astring_20_3e_20_3e_19',['vector&lt; std::pair&lt; int, std::string &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3ashared_5fptr_20_3e_20',['vector&lt; std::shared_ptr &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3ashared_5fptr_3c_20spdlog_3a_3asinks_3a_3asink_20_3e_20_3e_21',['vector&lt; std::shared_ptr&lt; spdlog::sinks::sink &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3astring_20_3e_22',['vector&lt; std::string &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3athread_20_3e_23',['vector&lt; std::thread &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3aunique_5fptr_3c_20spdlog_3a_3adetails_3a_3aflag_5fformatter_20_3e_20_3e_24',['vector&lt; std::unique_ptr&lt; spdlog::details::flag_formatter &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20t_20_3e_25',['vector&lt; T &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['view_26',['view',['../structview.html',1,'']]],
  ['view_5ft_27',['view_t',['../structdetail_1_1range__to__view_3_01T_00_01enable__if__t_3_01has__const__begin__end_3_01T_01_4_1_1value_01_4_01_4_1_1view__t.html',1,'detail::range_to_view&lt; T, enable_if_t&lt; has_const_begin_end&lt; T &gt;::value &gt; &gt;::view_t'],['../structdetail_1_1range__to__view_3_01T_00_01enable__if__t_3_9has__const__begin__end_3_01T_01_4_1_1cf1f6c31b1fc849c7f6ab73440db946.html',1,'detail::range_to_view&lt; T, enable_if_t&lt;!has_const_begin_end&lt; T &gt;::value &amp;&amp;has_mutable_begin_end&lt; T &gt;::value &gt; &gt;::view_t']]],
  ['void_5ft_28',['void_t',['http://en.cppreference.com/w/cpp/types/void_t.html',1,'std']]]
];
