var searchData=
[
  ['s_5fformatter_0',['S_formatter',['../classspdlog_1_1details_1_1S__formatter.html',1,'spdlog::details']]],
  ['scoped_5fallocator_5fadaptor_1',['scoped_allocator_adaptor',['http://en.cppreference.com/w/cpp/memory/scoped_allocator_adaptor.html',1,'std']]],
  ['scoped_5fpadder_2',['scoped_padder',['../classspdlog_1_1details_1_1scoped__padder.html',1,'spdlog::details']]],
  ['scopedmessage_3',['ScopedMessage',['../classCatch_1_1ScopedMessage.html',1,'Catch']]],
  ['seconds_4',['seconds',['http://en.cppreference.com/w/cpp/chrono/duration.html',1,'std::chrono']]],
  ['section_5',['Section',['../classCatch_1_1Section.html',1,'Catch']]],
  ['sectionendinfo_6',['SectionEndInfo',['../structCatch_1_1SectionEndInfo.html',1,'Catch']]],
  ['sectioninfo_7',['SectionInfo',['../structCatch_1_1SectionInfo.html',1,'Catch']]],
  ['seed_5fseq_8',['seed_seq',['http://en.cppreference.com/w/cpp/numeric/random/seed_seq.html',1,'std']]],
  ['sentry_9',['sentry',['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::ostream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'std::istrstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::ostringstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::ostrstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::osyncstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::stringstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::strstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::wfstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'std::wifstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::wiostream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'std::wistream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'std::wistringstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::wofstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::wostream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::wostringstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::wosyncstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::wstringstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'std::istringstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::basic_fstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'std::basic_ifstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::basic_iostream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'std::basic_istream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'std::basic_istringstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::basic_ofstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::basic_ostream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::basic_ostringstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::basic_osyncstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::basic_stringstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::fstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'std::ifstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::iostream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'std::istream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::ofstream::sentry']]],
  ['sequenced_5fpolicy_10',['sequenced_policy',['http://en.cppreference.com/w/cpp/algorithm/execution_policy_tag_t.html',1,'std::execution']]],
  ['set_11',['set',['http://en.cppreference.com/w/cpp/container/set.html',1,'std::pmr::set'],['http://en.cppreference.com/w/cpp/container/set.html',1,'std::set']]],
  ['shared_5ffuture_12',['shared_future',['http://en.cppreference.com/w/cpp/thread/shared_future.html',1,'std']]],
  ['shared_5flock_13',['shared_lock',['http://en.cppreference.com/w/cpp/thread/shared_lock.html',1,'std']]],
  ['shared_5fmutex_14',['shared_mutex',['http://en.cppreference.com/w/cpp/thread/shared_mutex.html',1,'std']]],
  ['shared_5fptr_15',['shared_ptr',['http://en.cppreference.com/w/cpp/memory/shared_ptr.html',1,'std']]],
  ['shared_5fptr_3c_20catch_3a_3aitestinvoker_20_3e_16',['shared_ptr&lt; Catch::ITestInvoker &gt;',['http://en.cppreference.com/w/cpp/memory/shared_ptr.html',1,'std']]],
  ['shared_5fptr_3c_20spdlog_3a_3aasync_5flogger_20_3e_17',['shared_ptr&lt; spdlog::async_logger &gt;',['http://en.cppreference.com/w/cpp/memory/shared_ptr.html',1,'std']]],
  ['shared_5fptr_3c_20spdlog_3a_3adetails_3a_3athread_5fpool_20_3e_18',['shared_ptr&lt; spdlog::details::thread_pool &gt;',['http://en.cppreference.com/w/cpp/memory/shared_ptr.html',1,'std']]],
  ['shared_5fptr_3c_20spdlog_3a_3alogger_20_3e_19',['shared_ptr&lt; spdlog::logger &gt;',['http://en.cppreference.com/w/cpp/memory/shared_ptr.html',1,'std']]],
  ['shared_5ftimed_5fmutex_20',['shared_timed_mutex',['http://en.cppreference.com/w/cpp/thread/shared_timed_mutex.html',1,'std']]],
  ['short_5ffilename_5fformatter_21',['short_filename_formatter',['../classspdlog_1_1details_1_1short__filename__formatter.html',1,'spdlog::details']]],
  ['short_5flevel_5fformatter_22',['short_level_formatter',['../classspdlog_1_1details_1_1short__level__formatter.html',1,'spdlog::details']]],
  ['showdurations_23',['ShowDurations',['../structCatch_1_1ShowDurations.html',1,'Catch']]],
  ['shuffle_5forder_5fengine_24',['shuffle_order_engine',['http://en.cppreference.com/w/cpp/numeric/random/shuffle_order_engine.html',1,'std']]],
  ['sid_5ft_25',['sid_t',['../structspdlog_1_1sinks_1_1win__eventlog_1_1internal_1_1sid__t.html',1,'spdlog::sinks::win_eventlog::internal']]],
  ['sig_5fatomic_5ft_26',['sig_atomic_t',['http://en.cppreference.com/w/cpp/utility/program/sig_atomic_t.html',1,'std']]],
  ['singlevaluegenerator_27',['SingleValueGenerator',['../classCatch_1_1Generators_1_1SingleValueGenerator.html',1,'Catch::Generators']]],
  ['sink_28',['sink',['../classspdlog_1_1sinks_1_1sink.html',1,'spdlog::sinks']]],
  ['size_5ft_29',['size_t',['http://en.cppreference.com/w/cpp/types/size_t.html',1,'std']]],
  ['slice_30',['slice',['http://en.cppreference.com/w/cpp/numeric/valarray/slice.html',1,'std']]],
  ['slice_5farray_31',['slice_array',['http://en.cppreference.com/w/cpp/numeric/valarray/slice_array.html',1,'std']]],
  ['smatch_32',['smatch',['http://en.cppreference.com/w/cpp/regex/match_results.html',1,'std']]],
  ['source_5ffilename_5fformatter_33',['source_filename_formatter',['../classspdlog_1_1details_1_1source__filename__formatter.html',1,'spdlog::details']]],
  ['source_5ffuncname_5fformatter_34',['source_funcname_formatter',['../classspdlog_1_1details_1_1source__funcname__formatter.html',1,'spdlog::details']]],
  ['source_5flinenum_5fformatter_35',['source_linenum_formatter',['../classspdlog_1_1details_1_1source__linenum__formatter.html',1,'spdlog::details']]],
  ['source_5floc_36',['source_loc',['../structspdlog_1_1source__loc.html',1,'spdlog']]],
  ['source_5flocation_37',['source_location',['http://en.cppreference.com/w/cpp/experimental/source_location.html',1,'std::experimental']]],
  ['source_5flocation_5fformatter_38',['source_location_formatter',['../classspdlog_1_1details_1_1source__location__formatter.html',1,'spdlog::details']]],
  ['sourcelineinfo_39',['SourceLineInfo',['../structCatch_1_1SourceLineInfo.html',1,'Catch']]],
  ['space_5finfo_40',['space_info',['http://en.cppreference.com/w/cpp/filesystem/space_info.html',1,'std::filesystem::space_info'],['http://en.cppreference.com/w/cpp/experimental/fs/space_info.html',1,'std::experimental::filesystem::space_info']]],
  ['span_41',['span',['http://en.cppreference.com/w/cpp/container/span.html',1,'std']]],
  ['spdlog_5fex_42',['spdlog_ex',['../classspdlog_1_1spdlog__ex.html',1,'spdlog']]],
  ['spec_5fhandler_43',['spec_handler',['../structformatter_3_01std_1_1chrono_1_1duration_3_01Rep_00_01Period_01_4_00_01Char_01_4_1_1spec__handler.html',1,'formatter&lt; std::chrono::duration&lt; Rep, Period &gt;, Char &gt;']]],
  ['specs_5fchecker_44',['specs_checker',['../classspecs__checker.html',1,'']]],
  ['specs_5fhandler_45',['specs_handler',['../classspecs__handler.html',1,'']]],
  ['specs_5fsetter_46',['specs_setter',['../classspecs__setter.html',1,'']]],
  ['specs_5fsetter_3c_20parsecontext_3a_3achar_5ftype_20_3e_47',['specs_setter&lt; ParseContext::char_type &gt;',['../classspecs__setter.html',1,'']]],
  ['sregex_5fiterator_48',['sregex_iterator',['http://en.cppreference.com/w/cpp/regex/regex_iterator.html',1,'std']]],
  ['sregex_5ftoken_5fiterator_49',['sregex_token_iterator',['http://en.cppreference.com/w/cpp/regex/regex_token_iterator.html',1,'std']]],
  ['ssub_5fmatch_50',['ssub_match',['http://en.cppreference.com/w/cpp/regex/sub_match.html',1,'std']]],
  ['stack_51',['stack',['http://en.cppreference.com/w/cpp/container/stack.html',1,'std']]],
  ['startswithmatcher_52',['StartsWithMatcher',['../structCatch_1_1Matchers_1_1StdString_1_1StartsWithMatcher.html',1,'Catch::Matchers::StdString']]],
  ['state_5ftype_53',['state_type',['http://en.cppreference.com/w/cpp/locale/codecvt.html',1,'std::codecvt::state_type'],['http://en.cppreference.com/w/cpp/locale/codecvt.html',1,'std::codecvt_byname::state_type'],['http://en.cppreference.com/w/cpp/locale/codecvt.html',1,'std::codecvt_utf16::state_type'],['http://en.cppreference.com/w/cpp/locale/codecvt.html',1,'std::codecvt_utf8::state_type'],['http://en.cppreference.com/w/cpp/locale/codecvt.html',1,'std::codecvt_utf8_utf16::state_type']]],
  ['std_5fstring_5fview_54',['std_string_view',['../structstd__string__view.html',1,'']]],
  ['stderr_5fsink_55',['stderr_sink',['../classspdlog_1_1sinks_1_1stderr__sink.html',1,'spdlog::sinks']]],
  ['stdout_5fsink_56',['stdout_sink',['../classspdlog_1_1sinks_1_1stdout__sink.html',1,'spdlog::sinks']]],
  ['stdout_5fsink_5fbase_57',['stdout_sink_base',['../classspdlog_1_1sinks_1_1stdout__sink__base.html',1,'spdlog::sinks']]],
  ['steady_5fclock_58',['steady_clock',['http://en.cppreference.com/w/cpp/chrono/steady_clock.html',1,'std::chrono']]],
  ['stopwatch_59',['stopwatch',['../classspdlog_1_1stopwatch.html',1,'spdlog']]],
  ['streambuf_60',['streambuf',['http://en.cppreference.com/w/cpp/io/basic_streambuf.html',1,'std']]],
  ['streamendstop_61',['StreamEndStop',['../structCatch_1_1StreamEndStop.html',1,'Catch']]],
  ['streamoff_62',['streamoff',['http://en.cppreference.com/w/cpp/io/streamoff.html',1,'std']]],
  ['streampos_63',['streampos',['http://en.cppreference.com/w/cpp/io/fpos.html',1,'std']]],
  ['streamsize_64',['streamsize',['http://en.cppreference.com/w/cpp/io/streamsize.html',1,'std']]],
  ['string_65',['string',['http://en.cppreference.com/w/cpp/string/basic_string.html',1,'std::pmr::string'],['http://en.cppreference.com/w/cpp/string/basic_string.html',1,'std::string']]],
  ['string_5ftype_66',['string_type',['http://en.cppreference.com/w/cpp/locale/numpunct.html',1,'std::numpunct_byname::string_type'],['http://en.cppreference.com/w/cpp/locale/collate.html',1,'std::collate_byname::string_type'],['http://en.cppreference.com/w/cpp/locale/numpunct.html',1,'std::numpunct::string_type'],['http://en.cppreference.com/w/cpp/locale/moneypunct.html',1,'std::moneypunct_byname::string_type'],['http://en.cppreference.com/w/cpp/locale/moneypunct.html',1,'std::moneypunct::string_type'],['http://en.cppreference.com/w/cpp/locale/money_put.html',1,'std::money_put::string_type'],['http://en.cppreference.com/w/cpp/locale/money_get.html',1,'std::money_get::string_type'],['http://en.cppreference.com/w/cpp/locale/messages.html',1,'std::messages_byname::string_type'],['http://en.cppreference.com/w/cpp/locale/messages.html',1,'std::messages::string_type'],['http://en.cppreference.com/w/cpp/locale/collate.html',1,'std::collate::string_type']]],
  ['string_5fvalue_67',['string_value',['../structstring__value.html',1,'']]],
  ['string_5fvalue_3c_20char_5ftype_20_3e_68',['string_value&lt; char_type &gt;',['../structstring__value.html',1,'']]],
  ['string_5fview_69',['string_view',['http://en.cppreference.com/w/cpp/experimental/basic_string_view.html',1,'std::experimental::string_view'],['http://en.cppreference.com/w/cpp/string/basic_string_view.html',1,'std::string_view']]],
  ['stringbuf_70',['stringbuf',['http://en.cppreference.com/w/cpp/io/basic_stringbuf.html',1,'std']]],
  ['stringmaker_71',['StringMaker',['../structCatch_1_1StringMaker.html',1,'Catch']]],
  ['stringmaker_3c_20bool_20_3e_72',['StringMaker&lt; bool &gt;',['../structCatch_1_1StringMaker_3_01bool_01_4.html',1,'Catch']]],
  ['stringmaker_3c_20catch_3a_3adetail_3a_3aapprox_20_3e_73',['StringMaker&lt; Catch::Detail::Approx &gt;',['../structCatch_1_1StringMaker_3_01Catch_1_1Detail_1_1Approx_01_4.html',1,'Catch']]],
  ['stringmaker_3c_20char_20_2a_20_3e_74',['StringMaker&lt; char * &gt;',['../structCatch_1_1StringMaker_3_01char_01_5_01_4.html',1,'Catch']]],
  ['stringmaker_3c_20char_20_3e_75',['StringMaker&lt; char &gt;',['../structCatch_1_1StringMaker_3_01char_01_4.html',1,'Catch']]],
  ['stringmaker_3c_20char_20const_20_2a_20_3e_76',['StringMaker&lt; char const * &gt;',['../structCatch_1_1StringMaker_3_01char_01const_01_5_01_4.html',1,'Catch']]],
  ['stringmaker_3c_20char_5bsz_5d_3e_77',['StringMaker&lt; char[SZ]&gt;',['../structCatch_1_1StringMaker_3_01char_0fSZ_0e_4.html',1,'Catch']]],
  ['stringmaker_3c_20double_20_3e_78',['StringMaker&lt; double &gt;',['../structCatch_1_1StringMaker_3_01double_01_4.html',1,'Catch']]],
  ['stringmaker_3c_20float_20_3e_79',['StringMaker&lt; float &gt;',['../structCatch_1_1StringMaker_3_01float_01_4.html',1,'Catch']]],
  ['stringmaker_3c_20int_20_3e_80',['StringMaker&lt; int &gt;',['../structCatch_1_1StringMaker_3_01int_01_4.html',1,'Catch']]],
  ['stringmaker_3c_20long_20_3e_81',['StringMaker&lt; long &gt;',['../structCatch_1_1StringMaker_3_01long_01_4.html',1,'Catch']]],
  ['stringmaker_3c_20long_20long_20_3e_82',['StringMaker&lt; long long &gt;',['../structCatch_1_1StringMaker_3_01long_01long_01_4.html',1,'Catch']]],
  ['stringmaker_3c_20r_20c_3a_3a_2a_20_3e_83',['StringMaker&lt; R C::* &gt;',['../structCatch_1_1StringMaker_3_01R_01C_1_1_5_01_4.html',1,'Catch']]],
  ['stringmaker_3c_20r_2c_20typename_20std_3a_3aenable_5fif_3c_20is_5frange_3c_20r_20_3e_3a_3avalue_20_26_26_21_3a_3acatch_3a_3adetail_3a_3aisstreaminsertable_3c_20r_20_3e_3a_3avalue_20_3e_3a_3atype_20_3e_84',['StringMaker&lt; R, typename std::enable_if&lt; is_range&lt; R &gt;::value &amp;&amp;!::Catch::Detail::IsStreamInsertable&lt; R &gt;::value &gt;::type &gt;',['../structCatch_1_1StringMaker_3_01R_00_01typename_01std_1_1enable__if_3_01is__range_3_01R_01_4_1_1ve8233c20b54b69b4771fbd413409d181.html',1,'Catch']]],
  ['stringmaker_3c_20signed_20char_20_3e_85',['StringMaker&lt; signed char &gt;',['../structCatch_1_1StringMaker_3_01signed_01char_01_4.html',1,'Catch']]],
  ['stringmaker_3c_20signed_20char_5bsz_5d_3e_86',['StringMaker&lt; signed char[SZ]&gt;',['../structCatch_1_1StringMaker_3_01signed_01char_0fSZ_0e_4.html',1,'Catch']]],
  ['stringmaker_3c_20std_3a_3anullptr_5ft_20_3e_87',['StringMaker&lt; std::nullptr_t &gt;',['../structCatch_1_1StringMaker_3_01std_1_1nullptr__t_01_4.html',1,'Catch']]],
  ['stringmaker_3c_20std_3a_3astring_20_3e_88',['StringMaker&lt; std::string &gt;',['../structCatch_1_1StringMaker_3_01std_1_1string_01_4.html',1,'Catch']]],
  ['stringmaker_3c_20std_3a_3awstring_20_3e_89',['StringMaker&lt; std::wstring &gt;',['../structCatch_1_1StringMaker_3_01std_1_1wstring_01_4.html',1,'Catch']]],
  ['stringmaker_3c_20t_20_2a_20_3e_90',['StringMaker&lt; T * &gt;',['../structCatch_1_1StringMaker_3_01T_01_5_01_4.html',1,'Catch']]],
  ['stringmaker_3c_20t_5bsz_5d_3e_91',['StringMaker&lt; T[SZ]&gt;',['../structCatch_1_1StringMaker_3_01T_0fSZ_0e_4.html',1,'Catch']]],
  ['stringmaker_3c_20unsigned_20char_20_3e_92',['StringMaker&lt; unsigned char &gt;',['../structCatch_1_1StringMaker_3_01unsigned_01char_01_4.html',1,'Catch']]],
  ['stringmaker_3c_20unsigned_20char_5bsz_5d_3e_93',['StringMaker&lt; unsigned char[SZ]&gt;',['../structCatch_1_1StringMaker_3_01unsigned_01char_0fSZ_0e_4.html',1,'Catch']]],
  ['stringmaker_3c_20unsigned_20int_20_3e_94',['StringMaker&lt; unsigned int &gt;',['../structCatch_1_1StringMaker_3_01unsigned_01int_01_4.html',1,'Catch']]],
  ['stringmaker_3c_20unsigned_20long_20_3e_95',['StringMaker&lt; unsigned long &gt;',['../structCatch_1_1StringMaker_3_01unsigned_01long_01_4.html',1,'Catch']]],
  ['stringmaker_3c_20unsigned_20long_20long_20_3e_96',['StringMaker&lt; unsigned long long &gt;',['../structCatch_1_1StringMaker_3_01unsigned_01long_01long_01_4.html',1,'Catch']]],
  ['stringmaker_3c_20wchar_5ft_20_2a_20_3e_97',['StringMaker&lt; wchar_t * &gt;',['../structCatch_1_1StringMaker_3_01wchar__t_01_5_01_4.html',1,'Catch']]],
  ['stringmaker_3c_20wchar_5ft_20const_20_2a_20_3e_98',['StringMaker&lt; wchar_t const * &gt;',['../structCatch_1_1StringMaker_3_01wchar__t_01const_01_5_01_4.html',1,'Catch']]],
  ['stringmatcherbase_99',['StringMatcherBase',['../structCatch_1_1Matchers_1_1StdString_1_1StringMatcherBase.html',1,'Catch::Matchers::StdString']]],
  ['stringref_100',['StringRef',['../classCatch_1_1StringRef.html',1,'Catch']]],
  ['stringstream_101',['stringstream',['http://en.cppreference.com/w/cpp/io/basic_stringstream.html',1,'std']]],
  ['strong_5fequality_102',['strong_equality',['http://en.cppreference.com/w/cpp/utility/compare/strong_equality.html',1,'std']]],
  ['strong_5fordering_103',['strong_ordering',['http://en.cppreference.com/w/cpp/utility/compare/strong_ordering.html',1,'std']]],
  ['strstream_104',['strstream',['http://en.cppreference.com/w/cpp/io/strstream.html',1,'std']]],
  ['strstreambuf_105',['strstreambuf',['http://en.cppreference.com/w/cpp/io/strstreambuf.html',1,'std']]],
  ['student_5ft_5fdistribution_106',['student_t_distribution',['http://en.cppreference.com/w/cpp/numeric/random/student_t_distribution.html',1,'std']]],
  ['sub_5fmatch_107',['sub_match',['http://en.cppreference.com/w/cpp/regex/sub_match.html',1,'std']]],
  ['subtract_5fwith_5fcarry_5fengine_108',['subtract_with_carry_engine',['http://en.cppreference.com/w/cpp/numeric/random/subtract_with_carry_engine.html',1,'std']]],
  ['syncbuf_109',['syncbuf',['http://en.cppreference.com/w/cpp/io/basic_syncbuf.html',1,'std']]],
  ['synchronized_5fpool_5fresource_110',['synchronized_pool_resource',['http://en.cppreference.com/w/cpp/experimental/synchronized_pool_resource.html',1,'std::experimental::pmr::synchronized_pool_resource'],['http://en.cppreference.com/w/cpp/memory/synchronized_pool_resource.html',1,'std::pmr::synchronized_pool_resource']]],
  ['synchronous_5ffactory_111',['synchronous_factory',['../structspdlog_1_1synchronous__factory.html',1,'spdlog']]],
  ['syslog_5fsink_112',['syslog_sink',['../classspdlog_1_1sinks_1_1syslog__sink.html',1,'spdlog::sinks']]],
  ['system_5fclock_113',['system_clock',['http://en.cppreference.com/w/cpp/chrono/system_clock.html',1,'std::chrono']]],
  ['system_5ferror_114',['system_error',['http://en.cppreference.com/w/cpp/error/system_error.html',1,'std']]],
  ['systemd_5fsink_115',['systemd_sink',['../classspdlog_1_1sinks_1_1systemd__sink.html',1,'spdlog::sinks']]]
];
