var searchData=
[
  ['b_5fformatter_0',['b_formatter',['../classspdlog_1_1details_1_1B__formatter.html',1,'spdlog::details::B_formatter&lt; ScopedPadder &gt;'],['../classspdlog_1_1details_1_1b__formatter.html',1,'spdlog::details::b_formatter&lt; ScopedPadder &gt;']]],
  ['back_5finsert_5fiterator_1',['back_insert_iterator',['http://en.cppreference.com/w/cpp/iterator/back_insert_iterator.html',1,'std']]],
  ['back_5finsert_5fiterator_3c_20detail_3a_3abuffer_3c_20char_20_3e_20_3e_2',['back_insert_iterator&lt; detail::buffer&lt; char &gt; &gt;',['http://en.cppreference.com/w/cpp/iterator/back_insert_iterator.html',1,'std']]],
  ['backtracer_3',['backtracer',['../classspdlog_1_1details_1_1backtracer.html',1,'spdlog::details']]],
  ['bad_5falloc_4',['bad_alloc',['http://en.cppreference.com/w/cpp/memory/new/bad_alloc.html',1,'std']]],
  ['bad_5fany_5fcast_5',['bad_any_cast',['http://en.cppreference.com/w/cpp/utility/any/bad_any_cast.html',1,'std']]],
  ['bad_5farray_5fnew_5flength_6',['bad_array_new_length',['http://en.cppreference.com/w/cpp/memory/new/bad_array_new_length.html',1,'std']]],
  ['bad_5fcast_7',['bad_cast',['http://en.cppreference.com/w/cpp/types/bad_cast.html',1,'std']]],
  ['bad_5fexception_8',['bad_exception',['http://en.cppreference.com/w/cpp/error/bad_exception.html',1,'std']]],
  ['bad_5ffunction_5fcall_9',['bad_function_call',['http://en.cppreference.com/w/cpp/utility/functional/bad_function_call.html',1,'std']]],
  ['bad_5foptional_5faccess_10',['bad_optional_access',['http://en.cppreference.com/w/cpp/utility/optional/bad_optional_access.html',1,'std::bad_optional_access'],['http://en.cppreference.com/w/cpp/utility/optional/bad_optional_access.html',1,'std::experimental::bad_optional_access']]],
  ['bad_5ftypeid_11',['bad_typeid',['http://en.cppreference.com/w/cpp/types/bad_typeid.html',1,'std']]],
  ['bad_5fvariant_5faccess_12',['bad_variant_access',['http://en.cppreference.com/w/cpp/utility/variant/bad_variant_access.html',1,'std']]],
  ['bad_5fweak_5fptr_13',['bad_weak_ptr',['http://en.cppreference.com/w/cpp/memory/bad_weak_ptr.html',1,'std']]],
  ['base_5fsink_14',['base_sink',['../classspdlog_1_1sinks_1_1base__sink.html',1,'spdlog::sinks']]],
  ['base_5fsink_3c_20std_3a_3amutex_20_3e_15',['base_sink&lt; std::mutex &gt;',['../classspdlog_1_1sinks_1_1base__sink.html',1,'spdlog::sinks']]],
  ['basic_5fcommon_5freference_16',['basic_common_reference',['http://en.cppreference.com/w/cpp/types/common_reference.html',1,'std']]],
  ['basic_5fcstring_5fview_17',['basic_cstring_view',['../classbasic__cstring__view.html',1,'']]],
  ['basic_5fdata_18',['basic_data',['../structbasic__data.html',1,'']]],
  ['basic_5ffile_5fsink_19',['basic_file_sink',['../classspdlog_1_1sinks_1_1basic__file__sink.html',1,'spdlog::sinks']]],
  ['basic_5ffilebuf_20',['basic_filebuf',['http://en.cppreference.com/w/cpp/io/basic_filebuf.html',1,'std']]],
  ['basic_5fformat_5farg_21',['basic_format_arg',['../classbasic__format__arg.html',1,'']]],
  ['basic_5fformat_5fargs_22',['basic_format_args',['../classbasic__format__args.html',1,'']]],
  ['basic_5fformat_5fargs_3c_20basic_5fformat_5fcontext_20_3e_23',['basic_format_args&lt; basic_format_context &gt;',['../classbasic__format__args.html',1,'']]],
  ['basic_5fformat_5fargs_3c_20basic_5fprintf_5fcontext_20_3e_24',['basic_format_args&lt; basic_printf_context &gt;',['../classbasic__format__args.html',1,'']]],
  ['basic_5fformat_5fcontext_25',['basic_format_context',['../classbasic__format__context.html',1,'']]],
  ['basic_5fformat_5fcontext_3c_20char_20_3e_26',['basic_format_context&lt; Char &gt;',['../classbasic__format__context.html',1,'']]],
  ['basic_5fformat_5fparse_5fcontext_27',['basic_format_parse_context',['../classbasic__format__parse__context.html',1,'']]],
  ['basic_5fformat_5fparse_5fcontext_3c_20char_2c_20error_5fhandler_20_3e_28',['basic_format_parse_context&lt; Char, error_handler &gt;',['../classbasic__format__parse__context.html',1,'']]],
  ['basic_5fformat_5fparse_5fcontext_3c_20char_2c_20errorhandler_20_3e_29',['basic_format_parse_context&lt; Char, ErrorHandler &gt;',['../classbasic__format__parse__context.html',1,'']]],
  ['basic_5fformat_5fspecs_30',['basic_format_specs',['../structbasic__format__specs.html',1,'']]],
  ['basic_5fformat_5fspecs_3c_20char_5ftype_20_3e_31',['basic_format_specs&lt; char_type &gt;',['../structbasic__format__specs.html',1,'']]],
  ['basic_5fformat_5fspecs_3c_20parsecontext_3a_3achar_5ftype_20_3e_32',['basic_format_specs&lt; ParseContext::char_type &gt;',['../structbasic__format__specs.html',1,'']]],
  ['basic_5fformat_5fstring_33',['basic_format_string',['../classbasic__format__string.html',1,'']]],
  ['basic_5ffstream_34',['basic_fstream',['http://en.cppreference.com/w/cpp/io/basic_fstream.html',1,'std']]],
  ['basic_5fifstream_35',['basic_ifstream',['http://en.cppreference.com/w/cpp/io/basic_ifstream.html',1,'std']]],
  ['basic_5fios_36',['basic_ios',['http://en.cppreference.com/w/cpp/io/basic_ios.html',1,'std']]],
  ['basic_5fiostream_37',['basic_iostream',['http://en.cppreference.com/w/cpp/io/basic_iostream.html',1,'std']]],
  ['basic_5fistream_38',['basic_istream',['http://en.cppreference.com/w/cpp/io/basic_istream.html',1,'std']]],
  ['basic_5fistringstream_39',['basic_istringstream',['http://en.cppreference.com/w/cpp/io/basic_istringstream.html',1,'std']]],
  ['basic_5fmemory_5fbuffer_40',['basic_memory_buffer',['../classbasic__memory__buffer.html',1,'']]],
  ['basic_5fmemory_5fbuffer_3c_20bigit_2c_20bigits_5fcapacity_20_3e_41',['basic_memory_buffer&lt; bigit, bigits_capacity &gt;',['../classbasic__memory__buffer.html',1,'']]],
  ['basic_5fmemory_5fbuffer_3c_20wchar_5ft_20_3e_42',['basic_memory_buffer&lt; wchar_t &gt;',['../classbasic__memory__buffer.html',1,'']]],
  ['basic_5fofstream_43',['basic_ofstream',['http://en.cppreference.com/w/cpp/io/basic_ofstream.html',1,'std']]],
  ['basic_5fostream_44',['basic_ostream',['http://en.cppreference.com/w/cpp/io/basic_ostream.html',1,'std']]],
  ['basic_5fostream_3c_20char_20_3e_45',['basic_ostream&lt; Char &gt;',['http://en.cppreference.com/w/cpp/io/basic_ostream.html',1,'std']]],
  ['basic_5fostringstream_46',['basic_ostringstream',['http://en.cppreference.com/w/cpp/io/basic_ostringstream.html',1,'std']]],
  ['basic_5fosyncstream_47',['basic_osyncstream',['http://en.cppreference.com/w/cpp/io/basic_osyncstream.html',1,'std']]],
  ['basic_5fprintf_5fcontext_48',['basic_printf_context',['../classbasic__printf__context.html',1,'']]],
  ['basic_5fprintf_5fparse_5fcontext_49',['basic_printf_parse_context',['../classbasic__printf__parse__context.html',1,'']]],
  ['basic_5fregex_50',['basic_regex',['http://en.cppreference.com/w/cpp/regex/basic_regex.html',1,'std']]],
  ['basic_5fruntime_51',['basic_runtime',['../structbasic__runtime.html',1,'']]],
  ['basic_5fstreambuf_52',['basic_streambuf',['http://en.cppreference.com/w/cpp/io/basic_streambuf.html',1,'std']]],
  ['basic_5fstreambuf_3c_20char_20_3e_53',['basic_streambuf&lt; Char &gt;',['http://en.cppreference.com/w/cpp/io/basic_streambuf.html',1,'std']]],
  ['basic_5fstring_54',['basic_string',['http://en.cppreference.com/w/cpp/string/basic_string.html',1,'std']]],
  ['basic_5fstring_5fview_55',['basic_string_view',['../classbasic__string__view.html',1,'basic_string_view&lt; Char &gt;'],['http://en.cppreference.com/w/cpp/string/basic_string_view.html',1,'std::basic_string_view'],['http://en.cppreference.com/w/cpp/experimental/basic_string_view.html',1,'std::experimental::basic_string_view']]],
  ['basic_5fstring_5fview_3c_20char_20_3e_56',['basic_string_view&lt; char &gt;',['../classbasic__string__view.html',1,'']]],
  ['basic_5fstringbuf_57',['basic_stringbuf',['http://en.cppreference.com/w/cpp/io/basic_stringbuf.html',1,'std']]],
  ['basic_5fstringstream_58',['basic_stringstream',['http://en.cppreference.com/w/cpp/io/basic_stringstream.html',1,'std']]],
  ['basic_5fsyncbuf_59',['basic_syncbuf',['http://en.cppreference.com/w/cpp/io/basic_syncbuf.html',1,'std']]],
  ['benchmarklooper_60',['BenchmarkLooper',['../classCatch_1_1BenchmarkLooper.html',1,'Catch']]],
  ['bernoulli_5fdistribution_61',['bernoulli_distribution',['http://en.cppreference.com/w/cpp/numeric/random/bernoulli_distribution.html',1,'std']]],
  ['bidirectional_5fiterator_5ftag_62',['bidirectional_iterator_tag',['http://en.cppreference.com/w/cpp/iterator/iterator_tags.html',1,'std']]],
  ['big_5fdecimal_5ffp_63',['big_decimal_fp',['../structbig__decimal__fp.html',1,'']]],
  ['bigint_64',['bigint',['../classdetail_1_1bigint.html',1,'detail']]],
  ['binary_5ffunction_65',['binary_function',['http://en.cppreference.com/w/cpp/utility/functional/binary_function.html',1,'std']]],
  ['binary_5fnegate_66',['binary_negate',['http://en.cppreference.com/w/cpp/utility/functional/binary_negate.html',1,'std']]],
  ['binaryexpr_67',['BinaryExpr',['../classCatch_1_1BinaryExpr.html',1,'Catch']]],
  ['binomial_5fdistribution_68',['binomial_distribution',['http://en.cppreference.com/w/cpp/numeric/random/binomial_distribution.html',1,'std']]],
  ['bit_5fand_69',['bit_and',['http://en.cppreference.com/w/cpp/utility/functional/bit_and.html',1,'std']]],
  ['bit_5fnot_70',['bit_not',['http://en.cppreference.com/w/cpp/utility/functional/bit_not.html',1,'std']]],
  ['bit_5for_71',['bit_or',['http://en.cppreference.com/w/cpp/utility/functional/bit_or.html',1,'std']]],
  ['bit_5fxor_72',['bit_xor',['http://en.cppreference.com/w/cpp/utility/functional/bit_xor.html',1,'std']]],
  ['bits_73',['bits',['../structdetail_1_1bits.html',1,'detail']]],
  ['bitset_74',['bitset',['http://en.cppreference.com/w/cpp/utility/bitset.html',1,'std']]],
  ['bool_5fconstant_75',['bool_constant',['http://en.cppreference.com/w/cpp/types/integral_constant.html',1,'std']]],
  ['boundaries_76',['boundaries',['../structdetail_1_1boundaries.html',1,'detail']]],
  ['boyer_5fmoore_5fhorspool_5fsearcher_77',['boyer_moore_horspool_searcher',['http://en.cppreference.com/w/cpp/experimental/boyer_moore_horspool_searcher.html',1,'std::experimental::boyer_moore_horspool_searcher'],['http://en.cppreference.com/w/cpp/utility/functional/boyer_moore_horspool_searcher.html',1,'std::boyer_moore_horspool_searcher']]],
  ['boyer_5fmoore_5fsearcher_78',['boyer_moore_searcher',['http://en.cppreference.com/w/cpp/utility/functional/boyer_moore_searcher.html',1,'std::boyer_moore_searcher'],['http://en.cppreference.com/w/cpp/experimental/boyer_moore_searcher.html',1,'std::experimental::boyer_moore_searcher']]],
  ['buffer_79',['buffer',['../classbuffer.html',1,'']]],
  ['buffer_3c_20char_20_3e_80',['buffer&lt; char &gt;',['../classbuffer.html',1,'buffer&lt; Char &gt;'],['../classbuffer.html',1,'buffer&lt; char &gt;']]],
  ['buffer_3c_20container_3a_3avalue_5ftype_20_3e_81',['buffer&lt; Container::value_type &gt;',['../classbuffer.html',1,'']]],
  ['buffer_5ftraits_82',['buffer_traits',['../structbuffer__traits.html',1,'']]],
  ['buffered_5ffile_83',['buffered_file',['../classbuffered__file.html',1,'']]],
  ['byte_84',['byte',['http://en.cppreference.com/w/cpp/types/byte.html',1,'std']]],
  ['bytes_85',['bytes',['../classbytes.html',1,'']]]
];
