var searchData=
[
  ['u16streampos_0',['u16streampos',['http://en.cppreference.com/w/cpp/io/fpos.html',1,'std']]],
  ['u16string_1',['u16string',['http://en.cppreference.com/w/cpp/string/basic_string.html',1,'std::pmr::u16string'],['http://en.cppreference.com/w/cpp/string/basic_string.html',1,'std::u16string']]],
  ['u16string_5fview_2',['u16string_view',['http://en.cppreference.com/w/cpp/experimental/basic_string_view.html',1,'std::experimental::u16string_view'],['http://en.cppreference.com/w/cpp/string/basic_string_view.html',1,'std::u16string_view']]],
  ['u32streampos_3',['u32streampos',['http://en.cppreference.com/w/cpp/io/fpos.html',1,'std']]],
  ['u32string_4',['u32string',['http://en.cppreference.com/w/cpp/string/basic_string.html',1,'std::pmr::u32string'],['http://en.cppreference.com/w/cpp/string/basic_string.html',1,'std::u32string']]],
  ['u32string_5fview_5',['u32string_view',['http://en.cppreference.com/w/cpp/experimental/basic_string_view.html',1,'std::experimental::u32string_view'],['http://en.cppreference.com/w/cpp/string/basic_string_view.html',1,'std::u32string_view']]],
  ['u8string_6',['u8string',['http://en.cppreference.com/w/cpp/string/basic_string.html',1,'std::pmr::u8string'],['http://en.cppreference.com/w/cpp/string/basic_string.html',1,'std::u8string']]],
  ['u8string_5fview_7',['u8string_view',['http://en.cppreference.com/w/cpp/string/basic_string_view.html',1,'std']]],
  ['uint128_5fwrapper_8',['uint128_wrapper',['../structdetail_1_1uint128__wrapper.html',1,'detail']]],
  ['uint16_5ft_9',['uint16_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint32_5ft_10',['uint32_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint64_5ft_11',['uint64_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint8_5ft_12',['uint8_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint_5ffast16_5ft_13',['uint_fast16_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint_5ffast32_5ft_14',['uint_fast32_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint_5ffast64_5ft_15',['uint_fast64_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint_5ffast8_5ft_16',['uint_fast8_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint_5fleast16_5ft_17',['uint_least16_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint_5fleast32_5ft_18',['uint_least32_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint_5fleast64_5ft_19',['uint_least64_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint_5fleast8_5ft_20',['uint_least8_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uintmax_5ft_21',['uintmax_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uintptr_5ft_22',['uintptr_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['unary_5ffunction_23',['unary_function',['http://en.cppreference.com/w/cpp/utility/functional/unary_function.html',1,'std']]],
  ['unary_5fnegate_24',['unary_negate',['http://en.cppreference.com/w/cpp/utility/functional/unary_negate.html',1,'std']]],
  ['unaryexpr_25',['UnaryExpr',['../classCatch_1_1UnaryExpr.html',1,'Catch']]],
  ['underflow_5ferror_26',['underflow_error',['http://en.cppreference.com/w/cpp/error/underflow_error.html',1,'std']]],
  ['underlying_5ftype_27',['underlying_type',['http://en.cppreference.com/w/cpp/types/underlying_type.html',1,'std']]],
  ['underlying_5ftype_5ft_28',['underlying_type_t',['http://en.cppreference.com/w/cpp/types/underlying_type.html',1,'std']]],
  ['unexpected_5fhandler_29',['unexpected_handler',['http://en.cppreference.com/w/cpp/error/unexpected_handler.html',1,'std']]],
  ['unformattable_30',['unformattable',['../structunformattable.html',1,'']]],
  ['uniform_5fint_5fdistribution_31',['uniform_int_distribution',['http://en.cppreference.com/w/cpp/numeric/random/uniform_int_distribution.html',1,'std']]],
  ['uniform_5fint_5fdistribution_3c_20integer_20_3e_32',['uniform_int_distribution&lt; Integer &gt;',['http://en.cppreference.com/w/cpp/numeric/random/uniform_int_distribution.html',1,'std']]],
  ['uniform_5freal_5fdistribution_33',['uniform_real_distribution',['http://en.cppreference.com/w/cpp/numeric/random/uniform_real_distribution.html',1,'std']]],
  ['uniform_5freal_5fdistribution_3c_20float_20_3e_34',['uniform_real_distribution&lt; Float &gt;',['http://en.cppreference.com/w/cpp/numeric/random/uniform_real_distribution.html',1,'std']]],
  ['unique_5flock_35',['unique_lock',['http://en.cppreference.com/w/cpp/thread/unique_lock.html',1,'std']]],
  ['unique_5fptr_36',['unique_ptr',['http://en.cppreference.com/w/cpp/memory/unique_ptr.html',1,'std']]],
  ['unique_5fptr_3c_20catch_3a_3agenerators_3a_3aigenerator_3c_20t_20_3e_20_3e_37',['unique_ptr&lt; Catch::Generators::IGenerator&lt; T &gt; &gt;',['http://en.cppreference.com/w/cpp/memory/unique_ptr.html',1,'std']]],
  ['unique_5fptr_3c_20catch_3a_3agenerators_3a_3aigenerator_3c_20u_20_3e_20_3e_38',['unique_ptr&lt; Catch::Generators::IGenerator&lt; U &gt; &gt;',['http://en.cppreference.com/w/cpp/memory/unique_ptr.html',1,'std']]],
  ['unique_5fptr_3c_20detail_3a_3adynamic_5farg_5flist_3a_3anode_3c_3e_20_3e_39',['unique_ptr&lt; detail::dynamic_arg_list::node&lt;&gt; &gt;',['http://en.cppreference.com/w/cpp/memory/unique_ptr.html',1,'std']]],
  ['unique_5fptr_3c_20mongocxx_3a_3aclient_20_3e_40',['unique_ptr&lt; mongocxx::client &gt;',['http://en.cppreference.com/w/cpp/memory/unique_ptr.html',1,'std']]],
  ['unique_5fptr_3c_20spdlog_3a_3adetails_3a_3aperiodic_5fworker_20_3e_41',['unique_ptr&lt; spdlog::details::periodic_worker &gt;',['http://en.cppreference.com/w/cpp/memory/unique_ptr.html',1,'std']]],
  ['unique_5fptr_3c_20spdlog_3a_3aformatter_20_3e_42',['unique_ptr&lt; spdlog::formatter &gt;',['http://en.cppreference.com/w/cpp/memory/unique_ptr.html',1,'std']]],
  ['unordered_5fmap_43',['unordered_map',['http://en.cppreference.com/w/cpp/container/unordered_map.html',1,'std::pmr::unordered_map'],['http://en.cppreference.com/w/cpp/container/unordered_map.html',1,'std::unordered_map']]],
  ['unordered_5fmap_3c_20char_2c_20std_3a_3aunique_5fptr_3c_20custom_5fflag_5fformatter_20_3e_20_3e_44',['unordered_map&lt; char, std::unique_ptr&lt; custom_flag_formatter &gt; &gt;',['http://en.cppreference.com/w/cpp/container/unordered_map.html',1,'std']]],
  ['unordered_5fmap_3c_20std_3a_3astring_2c_20level_3a_3alevel_5fenum_20_3e_45',['unordered_map&lt; std::string, level::level_enum &gt;',['http://en.cppreference.com/w/cpp/container/unordered_map.html',1,'std']]],
  ['unordered_5fmap_3c_20std_3a_3astring_2c_20std_3a_3ashared_5fptr_3c_20spdlog_3a_3alogger_20_3e_20_3e_46',['unordered_map&lt; std::string, std::shared_ptr&lt; spdlog::logger &gt; &gt;',['http://en.cppreference.com/w/cpp/container/unordered_map.html',1,'std']]],
  ['unordered_5fmultimap_47',['unordered_multimap',['http://en.cppreference.com/w/cpp/container/unordered_multimap.html',1,'std::pmr::unordered_multimap'],['http://en.cppreference.com/w/cpp/container/unordered_multimap.html',1,'std::unordered_multimap']]],
  ['unordered_5fmultiset_48',['unordered_multiset',['http://en.cppreference.com/w/cpp/container/unordered_multiset.html',1,'std::pmr::unordered_multiset'],['http://en.cppreference.com/w/cpp/container/unordered_multiset.html',1,'std::unordered_multiset']]],
  ['unordered_5fset_49',['unordered_set',['http://en.cppreference.com/w/cpp/container/unordered_set.html',1,'std::pmr::unordered_set'],['http://en.cppreference.com/w/cpp/container/unordered_set.html',1,'std::unordered_set']]],
  ['unorderedequalsmatcher_50',['UnorderedEqualsMatcher',['../structCatch_1_1Matchers_1_1Vector_1_1UnorderedEqualsMatcher.html',1,'Catch::Matchers::Vector']]],
  ['unsequenced_5fpolicy_51',['unsequenced_policy',['http://en.cppreference.com/w/cpp/algorithm/execution_policy_tag_t.html',1,'std::execution']]],
  ['unsynchronized_5fpool_5fresource_52',['unsynchronized_pool_resource',['http://en.cppreference.com/w/cpp/experimental/unsynchronized_pool_resource.html',1,'std::experimental::pmr::unsynchronized_pool_resource'],['http://en.cppreference.com/w/cpp/memory/unsynchronized_pool_resource.html',1,'std::pmr::unsynchronized_pool_resource']]],
  ['unwrap_5fref_5fdecay_53',['unwrap_ref_decay',['http://en.cppreference.com/w/cpp/utility/functional/unwrap_reference.html',1,'std']]],
  ['unwrap_5fref_5fdecay_5ft_54',['unwrap_ref_decay_t',['http://en.cppreference.com/w/cpp/utility/functional/unwrap_reference.html',1,'std']]],
  ['unwrap_5freference_55',['unwrap_reference',['http://en.cppreference.com/w/cpp/utility/functional/unwrap_reference.html',1,'std']]],
  ['usecolour_56',['UseColour',['../structCatch_1_1UseColour.html',1,'Catch']]],
  ['uses_5fallocator_57',['uses_allocator',['http://en.cppreference.com/w/cpp/memory/uses_allocator.html',1,'std']]],
  ['utf8_5fto_5futf16_58',['utf8_to_utf16',['../classutf8__to__utf16.html',1,'']]]
];
