on:
    push:
        tags:
            - '**'

jobs:
    gh_pages:
        uses: asherikov/ccws/.github/workflows/reusable_dox.yaml@master
        with:
            distro: noble
            version: ${{ github.ref_name }}
            push: false
        permissions:
            contents: write

    deb_noble:
        uses: asherikov/ccws/.github/workflows/reusable_deb.yaml@master
        with:
            distro: noble
            workspace_github_repo: asherikov/px4ws
            workspace_version: ${{ github.sha }}
            cloudsmith_repo: asherikov-aV7/all/ubuntu/noble
            build_target: "PKG='px4sitl px4_offboard_demo_py'"
        secrets:
            cloudsmith_token: ${{ secrets.CLOUDSMITH_API_KEY }}
